### ISSUE TITLE
Incorrect opcodes

### ISSUE THREAD

**Issue by achille-fouilleul** [moxielogic/moxielogic.github.io#1]
I think there are a few mistakes on the architecture page:

bgtu: 1100101vvvvvvvvv
ld.s: 00010001AAAABBBB
lda.s: 00010011AAAAxxxx
mul.x: 00010100AAAABBBB
umul.x: 00010011AAAABBBB

According to binutils/opcodes/moxie-opc.c these should be:

bgtu: 110101vvvvvvvvvv
ld.s: 00100001AAAABBBB
lda.s: 00100010AAAAxxxx
mul.x: 00010101AAAABBBB
umul.x: 00010100AAAABBBB

**Comment by atgreen** [comment]
Thanks!  I've fixed these.
